### ISSUE TITLE
User exists validator

### ISSUE THREAD

**Issue by Tlapi** [goalio/GoalioForgotPassword#17] opened 2013-08-09 08:42 UTC
Hi,

there should be a validator to validate if user with given e-mail exists in db. Now, when i enter e-mail which does not exist, it will return "A reminder has been sent to your e-mail address *****". Thats not true at all.

**Comment by Tlapi** [comment] 2013-08-09 09:03
PR here: https://github.com/goalio/GoalioForgotPassword/pull/18

**Comment by pdobrigkeit** [comment] 2013-08-09 09:06
Hey Tlapi,

that was actually done by design. Otherwise it is possible to get valid e-mail addresses by simply using the reminder service. It would be nice if you could make this an optional thing enabled via the configuration.

**Comment by Tlapi** [comment] 2013-08-09 09:10
Hi!

yes, that is what i was also thinking about, but then i realised that you can get valid e-mail addresses the same way, when you try to register and zfcuser will tell you that "this e-mail is already registered" right?

But maybe i can make it optional.

**Comment by Tlapi** [comment] 2013-08-09 09:31
Okay, i have made it optional.

You can use `'validate_existing_record' => true` in your config now.

**Comment by pdobrigkeit** [comment] 2013-08-09 09:56
Merged PR

**Closed as completed by pdobrigkeit** 2013-08-09 09:56 UTC
